name: Build and Release

permissions: write-all # there is unfortunately no permission for releases.

on:
  push:
    branches: [ master ]
  release:
    types: [published]
  

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: setup node.js 19
        uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: install dependencies
        run: yarn install
      - name: build
        run: yarn build
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: Latest build
          files: |
            dist/spacerplace-userscript.user.js
            spacerplace-userscript-autoupdater.user.js
